[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "autils/_version.py"  
version_scheme = "post-release"  
local_scheme = "node-and-date"   